name: Deploy to Magalu Cloud Object Storage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '22.15.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Build application
      env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
        VITE_API_AUTH_URL: ${{ secrets.VITE_API_AUTH_URL }}
      run: npm run build

    - name: Deploy to Magalu Cloud Object Storage
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.MAGALU_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.MAGALU_SECRET_ACCESS_KEY }}
      run: |
        aws s3 sync dist/ s3://${{ secrets.MAGALU_BUCKET_NAME }} \
          --delete \
          --cache-control "public, max-age=31536000" \
          --exclude "*.html" \
          --exclude "*.json" \
          --endpoint-url ${{ secrets.MAGALU_ENDPOINT }}

        aws s3 sync dist/ s3://${{ secrets.MAGALU_BUCKET_NAME }} \
          --delete \
          --cache-control "no-cache, no-store, must-revalidate" \
          --include "*.html" \
          --include "*.json" \
          --endpoint-url ${{ secrets.MAGALU_ENDPOINT }}