name: Deploy to Magalu Cloud Object Storage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '22.15.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Build application
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.MAGALU_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.MAGALU_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.MAGALU_REGION || 'br-se1' }}
    
    - name: Deploy to Magalu Cloud Object Storage
      run: |
        aws s3 sync dist/ s3://${{ secrets.MAGALU_BUCKET_NAME }} \
          --delete \
          --cache-control "public, max-age=31536000" \
          --exclude "*.html" \
          --exclude "*.json" \
          --endpoint-url ${{ secrets.MAGALU_ENDPOINT }}

        aws s3 sync dist/ s3://${{ secrets.MAGALU_BUCKET_NAME }} \
          --delete \
          --cache-control "no-cache, no-store, must-revalidate" \
          --include "*.html" \
          --include "*.json" \
          --endpoint-url ${{ secrets.MAGALU_ENDPOINT }}
